/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50:  'rgb(var(--color-brand-50)  / <alpha-value>)',
          100: 'rgb(var(--color-brand-100) / <alpha-value>)',
          200: 'rgb(var(--color-brand-200) / <alpha-value>)',
          300: 'rgb(var(--color-brand-300) / <alpha-value>)',
          400: 'rgb(var(--color-brand-400) / <alpha-value>)',
          500: 'rgb(var(--color-brand-500) / <alpha-value>)',
          600: 'rgb(var(--color-brand-600) / <alpha-value>)',
          700: 'rgb(var(--color-brand-700) / <alpha-value>)',
          800: 'rgb(var(--color-brand-800) / <alpha-value>)',
          900: 'rgb(var(--color-brand-900) / <alpha-value>)',
          950: 'rgb(var(--color-brand-950) / <alpha-value>)',
        },
        navy: {
          50:  '#f0f4f8',
          100: '#dce5ef',
          200: '#b9cbe0',
          300: '#8aa9ca',
          400: '#5c84af',
          500: '#3d6690',
          600: '#1E3A5F',
          700: '#1a3254',
          800: '#152a46',
          900: '#0f1f34',
          950: '#081120',
        },
        cream: {
          DEFAULT: 'rgb(var(--color-cream)     / <alpha-value>)',
          50:     'rgb(var(--color-cream-50)  / <alpha-value>)',
          100:    'rgb(var(--color-cream)     / <alpha-value>)',
          200:    'rgb(var(--color-cream-200) / <alpha-value>)',
          300:    'rgb(var(--color-cream-300) / <alpha-value>)',
          400:    'rgb(var(--color-cream-400) / <alpha-value>)',
          500:    'rgb(var(--color-cream-500) / <alpha-value>)',
        },
        ink: {
          DEFAULT: 'rgb(var(--color-ink)     / <alpha-value>)',
          900:     'rgb(var(--color-ink-900) / <alpha-value>)',
          800:     'rgb(var(--color-ink-800) / <alpha-value>)',
          700:     'rgb(var(--color-ink-700) / <alpha-value>)',
          600:     'rgb(var(--color-ink-600) / <alpha-value>)',
          500:     'rgb(var(--color-ink-500) / <alpha-value>)',
          400:     'rgb(var(--color-ink-400) / <alpha-value>)',
          300:     'rgb(var(--color-ink-300) / <alpha-value>)',
          200:     'rgb(var(--color-ink-200) / <alpha-value>)',
          100:     'rgb(var(--color-ink-100) / <alpha-value>)',
          50:      'rgb(var(--color-ink-50)  / <alpha-value>)',
        },
        surface: {
          DEFAULT: 'rgb(var(--color-surface)       / <alpha-value>)',
          warm:    'rgb(var(--color-surface-warm)  / <alpha-value>)',
          muted:   'rgb(var(--color-surface-muted) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Instrument Serif', 'Georgia', 'serif'],
      },
      borderRadius: {
        'pill': '9999px',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        'soft':    'var(--shadow-soft)',
        'soft-md': 'var(--shadow-soft-md)',
        'soft-lg': '0 8px 32px rgba(0,0,0,0.09), 0 2px 8px rgba(0,0,0,0.05)',
        'glow':    'var(--shadow-glow)',
      },
    },
  },
  plugins: [],
}
