"""
SpotSEO - French SEO Footprints Seed Data
66+ footprints for netlinking prospection on French websites.

Each footprint uses Google search operators to find link-building opportunities.
Templates use {keyword} (always) and optionally {domain} as placeholders.
"""

FOOTPRINTS_SEED = [
    # =========================================================================
    # BLOG COMMENTS (10)
    # =========================================================================
    {
        "name": "WordPress - Commentaires ouverts FR",
        "category": "blog_comments",
        "subcategory": "WordPress",
        "query_template": '"{keyword}" "laisser un commentaire" inurl:blog site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "WordPress",
        "language": "fr",
        "description": "Blogs WordPress francophones avec commentaires ouverts via la mention laisser un commentaire",
        "tags": ["wordpress", "commentaires", "blog", "fr"],
    },
    {
        "name": "WordPress - Formulaire commentaire FR",
        "category": "blog_comments",
        "subcategory": "WordPress",
        "query_template": '"{keyword}" "votre adresse e-mail ne sera pas publiee" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "WordPress",
        "language": "fr",
        "description": "Blogs WordPress FR identifiables par le message standard du formulaire de commentaires",
        "tags": ["wordpress", "commentaires", "formulaire", "fr"],
    },
    {
        "name": "WordPress - Commentaires recents FR",
        "category": "blog_comments",
        "subcategory": "WordPress",
        "query_template": '"{keyword}" "commentaires recents" inurl:wp site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "WordPress",
        "language": "fr",
        "description": "Blogs WordPress FR affichant un widget de commentaires recents, signe de commentaires actifs",
        "tags": ["wordpress", "commentaires", "actif", "fr"],
    },
    {
        "name": "WordPress - Repondre commentaire FR",
        "category": "blog_comments",
        "subcategory": "WordPress",
        "query_template": '"{keyword}" "connectez-vous pour repondre" OR "laisser une reponse" inurl:blog',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "WordPress",
        "language": "fr",
        "description": "Blogs WordPress FR avec fils de commentaires ouverts aux reponses",
        "tags": ["wordpress", "commentaires", "reponse", "fr"],
    },
    {
        "name": "Blogger - Commentaires FR",
        "category": "blog_comments",
        "subcategory": "Blogger",
        "query_template": '"{keyword}" "publier un commentaire" site:blogspot.com',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "Blogger",
        "language": "fr",
        "description": "Blogs Blogger/Blogspot francophones avec commentaires ouverts",
        "tags": ["blogger", "blogspot", "commentaires", "fr"],
    },
    {
        "name": "Blogger - Enregistrer commentaire FR",
        "category": "blog_comments",
        "subcategory": "Blogger",
        "query_template": '"{keyword}" "enregistrer un commentaire" site:blogspot.fr OR site:blogspot.com',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "Blogger",
        "language": "fr",
        "description": "Blogs Blogger FR avec formulaire de commentaires actif",
        "tags": ["blogger", "commentaires", "fr"],
    },
    {
        "name": "Blog generique - Ajouter commentaire FR",
        "category": "blog_comments",
        "subcategory": None,
        "query_template": '"{keyword}" "ajouter un commentaire" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Blogs francophones generiques avec commentaires ouverts",
        "tags": ["blog", "commentaires", "generique", "fr"],
    },
    {
        "name": "Blog generique - Site web dans commentaire FR",
        "category": "blog_comments",
        "subcategory": None,
        "query_template": '"{keyword}" "nom" "e-mail" "site web" "commentaire" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Blogs FR avec formulaire de commentaire incluant un champ site web",
        "tags": ["blog", "commentaires", "site-web", "fr"],
    },
    {
        "name": "Blog Over-blog commentaires FR",
        "category": "blog_comments",
        "subcategory": "Over-blog",
        "query_template": '"{keyword}" "commenter cet article" site:over-blog.com',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "Over-blog",
        "language": "fr",
        "description": "Blogs Over-blog francophones avec commentaires ouverts",
        "tags": ["over-blog", "commentaires", "fr"],
    },
    {
        "name": "Blog CanalBlog commentaires FR",
        "category": "blog_comments",
        "subcategory": "CanalBlog",
        "query_template": '"{keyword}" "poster un commentaire" site:canalblog.com',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "CanalBlog",
        "language": "fr",
        "description": "Blogs CanalBlog francophones avec commentaires ouverts",
        "tags": ["canalblog", "commentaires", "fr"],
    },

    # =========================================================================
    # FORUMS (10)
    # =========================================================================
    {
        "name": "phpBB - Forums FR",
        "category": "forums",
        "subcategory": "phpBB",
        "query_template": '"{keyword}" "powered by phpBB" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "medium",
        "platform_target": "phpBB",
        "language": "fr",
        "description": "Forums phpBB heberges sur des domaines .fr",
        "tags": ["phpbb", "forum", "fr"],
    },
    {
        "name": "phpBB - Repondre sujet FR",
        "category": "forums",
        "subcategory": "phpBB",
        "query_template": '"{keyword}" inurl:viewtopic.php "repondre" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "medium",
        "platform_target": "phpBB",
        "language": "fr",
        "description": "Sujets de forums phpBB FR ouverts aux reponses",
        "tags": ["phpbb", "forum", "repondre", "fr"],
    },
    {
        "name": "vBulletin - Forums FR",
        "category": "forums",
        "subcategory": "vBulletin",
        "query_template": '"{keyword}" "powered by vBulletin" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "medium",
        "platform_target": "vBulletin",
        "language": "fr",
        "description": "Forums vBulletin heberges sur des domaines francophones",
        "tags": ["vbulletin", "forum", "fr"],
    },
    {
        "name": "vBulletin - Discussions FR",
        "category": "forums",
        "subcategory": "vBulletin",
        "query_template": '"{keyword}" inurl:showthread.php site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "medium",
        "platform_target": "vBulletin",
        "language": "fr",
        "description": "Fils de discussion vBulletin sur domaines francophones",
        "tags": ["vbulletin", "forum", "discussion", "fr"],
    },
    {
        "name": "XenForo - Forums FR",
        "category": "forums",
        "subcategory": "XenForo",
        "query_template": '"{keyword}" "XenForo" inurl:threads site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "medium",
        "platform_target": "XenForo",
        "language": "fr",
        "description": "Forums XenForo francophones avec discussions ouvertes",
        "tags": ["xenforo", "forum", "fr"],
    },
    {
        "name": "XenForo - Repondre discussion FR",
        "category": "forums",
        "subcategory": "XenForo",
        "query_template": '"{keyword}" "repondre a la discussion" inurl:forums site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "medium",
        "platform_target": "XenForo",
        "language": "fr",
        "description": "Discussions XenForo FR ouvertes aux reponses",
        "tags": ["xenforo", "forum", "repondre", "fr"],
    },
    {
        "name": "Forumactif - Forums FR",
        "category": "forums",
        "subcategory": "Forumactif",
        "query_template": '"{keyword}" site:forumactif.com OR site:forumactif.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "Forumactif",
        "language": "fr",
        "description": "Forums heberges sur la plateforme Forumactif",
        "tags": ["forumactif", "forum", "fr"],
    },
    {
        "name": "Forumactif - Nouveau message FR",
        "category": "forums",
        "subcategory": "Forumactif",
        "query_template": '"{keyword}" "poster un nouveau sujet" site:forumactif.com',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "Forumactif",
        "language": "fr",
        "description": "Forums Forumactif ouverts a la creation de nouveaux sujets",
        "tags": ["forumactif", "forum", "nouveau-sujet", "fr"],
    },
    {
        "name": "Forum generique - Inscription FR",
        "category": "forums",
        "subcategory": None,
        "query_template": '"{keyword}" "inscription" "forum" "connectez-vous" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Forums francophones generiques avec inscription ouverte",
        "tags": ["forum", "inscription", "generique", "fr"],
    },
    {
        "name": "Forum generique - Signature FR",
        "category": "forums",
        "subcategory": None,
        "query_template": '"{keyword}" inurl:forum "profil" "signature" "site web" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Forums FR permettant d'ajouter un lien en signature de profil",
        "tags": ["forum", "signature", "profil", "fr"],
    },

    # =========================================================================
    # DIRECTORIES (8)
    # =========================================================================
    {
        "name": "Annuaire gratuit - Soumettre site FR",
        "category": "directories",
        "subcategory": "gratuit",
        "query_template": '"{keyword}" "soumettre un site" OR "proposer un site" inurl:annuaire',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Annuaires francophones gratuits acceptant les soumissions de sites",
        "tags": ["annuaire", "gratuit", "soumission", "fr"],
    },
    {
        "name": "Annuaire - Inscrire site FR",
        "category": "directories",
        "subcategory": "gratuit",
        "query_template": 'intitle:"annuaire" "{keyword}" "inscrire" OR "ajouter" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Annuaires FR avec formulaire d'inscription de site",
        "tags": ["annuaire", "inscrire", "fr"],
    },
    {
        "name": "Annuaire professionnel FR",
        "category": "directories",
        "subcategory": "professionnel",
        "query_template": '"{keyword}" "annuaire professionnel" "inscription gratuite" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Annuaires professionnels FR avec inscription gratuite",
        "tags": ["annuaire", "professionnel", "gratuit", "fr"],
    },
    {
        "name": "Annuaire thematique FR",
        "category": "directories",
        "subcategory": "thematique",
        "query_template": 'intitle:"annuaire" "{keyword}" "categorie" "description" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Annuaires thematiques FR classes par categories",
        "tags": ["annuaire", "thematique", "categorie", "fr"],
    },
    {
        "name": "Annuaire regional FR",
        "category": "directories",
        "subcategory": "regional",
        "query_template": '"{keyword}" "annuaire" "region" OR "departement" "ajouter" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Annuaires regionaux ou departementaux francophones",
        "tags": ["annuaire", "regional", "local", "fr"],
    },
    {
        "name": "Annuaire WordPress FR",
        "category": "directories",
        "subcategory": "gratuit",
        "query_template": '"{keyword}" "powered by WordPress" inurl:annuaire "soumettre"',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": "WordPress",
        "language": "fr",
        "description": "Annuaires construits sur WordPress avec soumission ouverte",
        "tags": ["annuaire", "wordpress", "soumission", "fr"],
    },
    {
        "name": "Annuaire entreprises FR",
        "category": "directories",
        "subcategory": "professionnel",
        "query_template": '"{keyword}" "annuaire entreprises" "referencer" OR "inscription" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Annuaires d'entreprises FR acceptant le referencement gratuit",
        "tags": ["annuaire", "entreprise", "referencement", "fr"],
    },
    {
        "name": "Annuaire web gratuit sans lien retour",
        "category": "directories",
        "subcategory": "gratuit",
        "query_template": '"{keyword}" "annuaire gratuit sans lien retour" "ajouter"',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Annuaires gratuits ne demandant pas de lien retour",
        "tags": ["annuaire", "gratuit", "sans-lien-retour", "fr"],
    },

    # =========================================================================
    # GUESTBOOKS (4)
    # =========================================================================
    {
        "name": "Livre d'or - Signer FR",
        "category": "guestbooks",
        "subcategory": None,
        "query_template": '"{keyword}" "signer le livre d\'or" OR "ecrire dans le livre d\'or" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Livres d'or francophones ouverts aux signatures",
        "tags": ["livre-dor", "guestbook", "signer", "fr"],
    },
    {
        "name": "Livre d'or - Ajouter message FR",
        "category": "guestbooks",
        "subcategory": None,
        "query_template": '"{keyword}" inurl:"livre-d-or" OR inurl:"livredor" "ajouter" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Pages de livres d'or FR identifiees par l'URL",
        "tags": ["livre-dor", "guestbook", "ajouter", "fr"],
    },
    {
        "name": "Livre d'or - Laisser message FR",
        "category": "guestbooks",
        "subcategory": None,
        "query_template": '"{keyword}" intitle:"livre d\'or" "laisser un message" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Livres d'or FR avec formulaire de message ouvert",
        "tags": ["livre-dor", "guestbook", "message", "fr"],
    },
    {
        "name": "Livre d'or - Site perso FR",
        "category": "guestbooks",
        "subcategory": None,
        "query_template": '"{keyword}" "livre d\'or" "votre site" "votre message" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Livres d'or de sites personnels FR avec champ URL",
        "tags": ["livre-dor", "guestbook", "site-perso", "fr"],
    },

    # =========================================================================
    # PROFILES (5)
    # =========================================================================
    {
        "name": "Profil utilisateur - Site web FR",
        "category": "profiles",
        "subcategory": None,
        "query_template": '"{keyword}" inurl:profil OR inurl:membre "site web" OR "site internet" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Pages de profils utilisateurs FR avec champ site web",
        "tags": ["profil", "membre", "site-web", "fr"],
    },
    {
        "name": "Profil forum - Page membre FR",
        "category": "profiles",
        "subcategory": None,
        "query_template": '"{keyword}" inurl:memberlist OR inurl:members "site web" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Pages de profils sur forums FR affichant le site web du membre",
        "tags": ["profil", "forum", "membre", "fr"],
    },
    {
        "name": "Profil communautaire FR",
        "category": "profiles",
        "subcategory": None,
        "query_template": '"{keyword}" "mon profil" "site web" "biographie" OR "a propos" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Profils communautaires FR avec champs biographie et site web",
        "tags": ["profil", "communaute", "biographie", "fr"],
    },
    {
        "name": "Profil Gravatar FR",
        "category": "profiles",
        "subcategory": "Gravatar",
        "query_template": '"{keyword}" site:gravatar.com inurl:profiles',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": "Gravatar",
        "language": "fr",
        "description": "Profils publics Gravatar avec lien vers site personnel",
        "tags": ["gravatar", "profil", "lien"],
    },
    {
        "name": "Profil About.me FR",
        "category": "profiles",
        "subcategory": "About.me",
        "query_template": '"{keyword}" site:about.me "france" OR "francais"',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": "About.me",
        "language": "fr",
        "description": "Profils About.me d'utilisateurs francophones avec lien sortant",
        "tags": ["about-me", "profil", "fr"],
    },

    # =========================================================================
    # SOCIAL (4)
    # =========================================================================
    {
        "name": "LinkedIn - Articles FR",
        "category": "social",
        "subcategory": "LinkedIn",
        "query_template": '"{keyword}" site:linkedin.com/pulse inurl:fr OR "france"',
        "expected_link_type": "nofollow",
        "difficulty": "medium",
        "platform_target": "LinkedIn",
        "language": "fr",
        "description": "Articles LinkedIn Pulse francophones pour commentaires et partage",
        "tags": ["linkedin", "pulse", "articles", "fr"],
    },
    {
        "name": "Facebook - Groupes publics FR",
        "category": "social",
        "subcategory": "Facebook",
        "query_template": '"{keyword}" site:facebook.com/groups inurl:permalink',
        "expected_link_type": "nofollow",
        "difficulty": "medium",
        "platform_target": "Facebook",
        "language": "fr",
        "description": "Publications dans des groupes Facebook publics francophones",
        "tags": ["facebook", "groupes", "fr"],
    },
    {
        "name": "Pinterest - Tableaux FR",
        "category": "social",
        "subcategory": "Pinterest",
        "query_template": '"{keyword}" site:pinterest.fr OR site:pinterest.com "epingle"',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "Pinterest",
        "language": "fr",
        "description": "Tableaux et epingles Pinterest francophones pour backlinks visuels",
        "tags": ["pinterest", "tableaux", "epingles", "fr"],
    },
    {
        "name": "Reddit - Discussions FR",
        "category": "social",
        "subcategory": "Reddit",
        "query_template": '"{keyword}" site:reddit.com/r/france OR site:reddit.com/r/francais',
        "expected_link_type": "nofollow",
        "difficulty": "hard",
        "platform_target": "Reddit",
        "language": "fr",
        "description": "Discussions sur les subreddits francophones pour referencer des ressources",
        "tags": ["reddit", "discussion", "fr"],
    },

    # =========================================================================
    # RESOURCE PAGES (5) - Pages with link lists where you can get featured
    # =========================================================================
    {
        "name": "Pages de ressources FR - Liens utiles",
        "category": "serp_exploration",
        "subcategory": "ressources",
        "query_template": '"{keyword}" intitle:"liens utiles" "ajouter" OR "suggerer" OR "proposer un lien" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Pages de liens utiles FR acceptant les suggestions de nouveaux liens",
        "tags": ["ressources", "liens", "soumission", "fr"],
    },
    {
        "name": "Blogs avec blogroll FR",
        "category": "blog_comments",
        "subcategory": None,
        "query_template": '"{keyword}" "blogroll" OR "blogs amis" OR "sites amis" "ajouter" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Blogs FR ayant une blogroll ou une page sites amis ouverte",
        "tags": ["blogroll", "sites-amis", "liens", "fr"],
    },
    {
        "name": "WordPress - Commentaires ouverts generiques",
        "category": "blog_comments",
        "subcategory": "WordPress",
        "query_template": '"{keyword}" "laisser un commentaire" "site web" "powered by WordPress"',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "WordPress",
        "language": "fr",
        "description": "Blogs WordPress tous TLD avec formulaire commentaire incluant champ site web",
        "tags": ["wordpress", "commentaires", "site-web", "international"],
    },
    {
        "name": "Forums avec inscription ouverte FR",
        "category": "forums",
        "subcategory": None,
        "query_template": '"{keyword}" "inscription gratuite" "forum" "poster" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Forums FR avec inscription gratuite et possibilite de poster",
        "tags": ["forum", "inscription", "poster", "fr"],
    },
    {
        "name": "Sites partenariats ouverts FR",
        "category": "guest_posts",
        "subcategory": None,
        "query_template": '"{keyword}" "devenir partenaire" OR "partenariat" "formulaire" OR "contact" inurl:partenaire site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Sites FR proposant des partenariats avec echange de liens",
        "tags": ["partenariat", "liens", "echange", "fr"],
    },

    # =========================================================================
    # SERP EXPLORATION (4)
    # =========================================================================
    {
        "name": "Recherche concurrents - Backlinks FR",
        "category": "serp_exploration",
        "subcategory": "concurrents",
        "query_template": '"{keyword}" "{domain}" -site:{domain} site:.fr',
        "expected_link_type": "mix",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Trouver les sites FR qui mentionnent un concurrent pour repliquer leurs backlinks",
        "tags": ["concurrent", "backlinks", "recherche", "fr"],
    },
    {
        "name": "Pages de ressources FR",
        "category": "serp_exploration",
        "subcategory": "ressources",
        "query_template": '"{keyword}" intitle:"ressources utiles" OR intitle:"liens utiles" OR intitle:"sites recommandes" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Pages de ressources et liens recommandes sur le sujet cible",
        "tags": ["ressources", "liens", "recommandes", "fr"],
    },
    {
        "name": "Listes top sites FR",
        "category": "serp_exploration",
        "subcategory": "listes",
        "query_template": '"{keyword}" intitle:"top" OR intitle:"meilleurs" "sites" OR "outils" OR "ressources" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Articles de type liste (top sites, meilleurs outils) pour etre reference",
        "tags": ["top", "liste", "meilleurs", "fr"],
    },
    {
        "name": "Concurrents - Ou sont-ils cites FR",
        "category": "serp_exploration",
        "subcategory": "concurrents",
        "query_template": 'intext:"{domain}" "{keyword}" -site:{domain} -site:facebook.com -site:twitter.com',
        "expected_link_type": "mix",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Identifier toutes les pages citant un concurrent pour opportunites similaires",
        "tags": ["concurrent", "mentions", "veille", "fr"],
    },

    # =========================================================================
    # GUEST POSTS (4)
    # =========================================================================
    {
        "name": "Articles invites FR - Proposer",
        "category": "guest_posts",
        "subcategory": None,
        "query_template": '"{keyword}" "article invite" OR "auteur invite" "proposer" OR "soumettre" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "hard",
        "platform_target": None,
        "language": "fr",
        "description": "Blogs FR acceptant les articles invites / guest posts",
        "tags": ["article-invite", "guest-post", "proposer", "fr"],
    },
    {
        "name": "Devenir redacteur FR",
        "category": "guest_posts",
        "subcategory": None,
        "query_template": '"{keyword}" "devenir redacteur" OR "ecrire pour nous" OR "contribuer" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "hard",
        "platform_target": None,
        "language": "fr",
        "description": "Sites FR cherchant des contributeurs ou redacteurs externes",
        "tags": ["redacteur", "contributeur", "guest-post", "fr"],
    },
    {
        "name": "Publier article FR",
        "category": "guest_posts",
        "subcategory": None,
        "query_template": '"{keyword}" "publiez votre article" OR "partagez votre expertise" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "hard",
        "platform_target": None,
        "language": "fr",
        "description": "Plateformes FR invitant a publier du contenu expert",
        "tags": ["publier", "expertise", "guest-post", "fr"],
    },
    {
        "name": "Tribune ouverte FR",
        "category": "guest_posts",
        "subcategory": None,
        "query_template": '"{keyword}" "tribune" "soumettre" OR "proposer" OR "contact" inurl:blog site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "hard",
        "platform_target": None,
        "language": "fr",
        "description": "Blogs FR acceptant des tribunes d'experts sur leur sujet",
        "tags": ["tribune", "expert", "guest-post", "fr"],
    },

    # =========================================================================
    # WEB 2.0 (4)
    # =========================================================================
    {
        "name": "Medium - Articles FR",
        "category": "web20",
        "subcategory": "Medium",
        "query_template": '"{keyword}" site:medium.com "france" OR "francais" OR "@"',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "Medium",
        "language": "fr",
        "description": "Articles Medium francophones pour commenter et referencer",
        "tags": ["medium", "web20", "articles", "fr"],
    },
    {
        "name": "Tumblr - Blogs FR",
        "category": "web20",
        "subcategory": "Tumblr",
        "query_template": '"{keyword}" site:tumblr.com "france" OR "francais"',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": "Tumblr",
        "language": "fr",
        "description": "Blogs Tumblr francophones pour creation de contenu avec liens",
        "tags": ["tumblr", "web20", "blog", "fr"],
    },
    {
        "name": "Scoop.it - Topics FR",
        "category": "web20",
        "subcategory": "Scoop.it",
        "query_template": '"{keyword}" site:scoop.it "france" OR "francais"',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": "Scoop.it",
        "language": "fr",
        "description": "Topics Scoop.it francophones pour curation de contenu avec liens",
        "tags": ["scoopit", "web20", "curation", "fr"],
    },
    {
        "name": "Pearltrees - Collections FR",
        "category": "web20",
        "subcategory": "Pearltrees",
        "query_template": '"{keyword}" site:pearltrees.com "france" OR "francais"',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": "Pearltrees",
        "language": "fr",
        "description": "Collections Pearltrees francophones pour curation collaborative",
        "tags": ["pearltrees", "web20", "curation", "fr"],
    },

    # =========================================================================
    # WIKIS (2)
    # =========================================================================
    {
        "name": "Wikis editables FR",
        "category": "wikis",
        "subcategory": None,
        "query_template": '"{keyword}" "modifier" OR "editer cette page" inurl:wiki site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "medium",
        "platform_target": None,
        "language": "fr",
        "description": "Wikis francophones editables pour ajout de references et liens",
        "tags": ["wiki", "editable", "references", "fr"],
    },
    {
        "name": "MediaWiki - Sites FR",
        "category": "wikis",
        "subcategory": "MediaWiki",
        "query_template": '"{keyword}" "powered by MediaWiki" OR inurl:"index.php?title=" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "medium",
        "platform_target": "MediaWiki",
        "language": "fr",
        "description": "Sites sous MediaWiki en .fr pour contribution et ajout de sources",
        "tags": ["mediawiki", "wiki", "sources", "fr"],
    },

    # =========================================================================
    # E-REPUTATION (4)
    # =========================================================================
    {
        "name": "Trustpilot - Avis FR",
        "category": "ereputation",
        "subcategory": "Trustpilot",
        "query_template": '"{keyword}" site:trustpilot.com/review inurl:fr OR "france"',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "Trustpilot",
        "language": "fr",
        "description": "Pages d'avis Trustpilot pour entreprises francophones",
        "tags": ["trustpilot", "avis", "ereputation", "fr"],
    },
    {
        "name": "Pages Jaunes - Avis FR",
        "category": "ereputation",
        "subcategory": "Pages Jaunes",
        "query_template": '"{keyword}" site:pagesjaunes.fr "avis" OR "noter"',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "Pages Jaunes",
        "language": "fr",
        "description": "Fiches entreprises Pages Jaunes avec section avis",
        "tags": ["pagesjaunes", "avis", "ereputation", "fr"],
    },
    {
        "name": "Comparateurs FR - Avis clients",
        "category": "ereputation",
        "subcategory": None,
        "query_template": '"{keyword}" "avis clients" OR "avis utilisateurs" "noter" OR "donner votre avis" site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Sites comparateurs et d'avis clients francophones",
        "tags": ["comparateur", "avis", "clients", "ereputation", "fr"],
    },
    {
        "name": "Google Maps - Avis locaux FR",
        "category": "ereputation",
        "subcategory": "Google",
        "query_template": '"{keyword}" site:google.com/maps "avis" "france"',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "Google Maps",
        "language": "fr",
        "description": "Fiches Google Maps d'entreprises FR pour le SEO local",
        "tags": ["google-maps", "avis", "local", "ereputation", "fr"],
    },

    # =========================================================================
    # ADDITIONAL ACTIONABLE SPOTS (4) - High conversion footprints
    # =========================================================================
    {
        "name": "WordPress - Commentaires avec champ URL (tous TLD)",
        "category": "blog_comments",
        "subcategory": "WordPress",
        "query_template": '"{keyword}" "votre adresse e-mail ne sera pas publiee" "site web"',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": "WordPress",
        "language": "fr",
        "description": "Blogs WordPress francophones avec champ URL dans le formulaire de commentaire",
        "tags": ["wordpress", "commentaires", "url", "tous-tld"],
    },
    {
        "name": "Annuaire gratuit sans validation FR",
        "category": "directories",
        "subcategory": "gratuit",
        "query_template": '"{keyword}" "annuaire gratuit" "ajouter un site" "validation automatique" OR "sans moderation"',
        "expected_link_type": "dofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Annuaires gratuits avec validation automatique des soumissions",
        "tags": ["annuaire", "gratuit", "auto-validation", "fr"],
    },
    {
        "name": "Forums generiques - Presentez-vous FR",
        "category": "forums",
        "subcategory": None,
        "query_template": '"{keyword}" "presentez-vous" OR "presentation des membres" inurl:forum site:.fr',
        "expected_link_type": "nofollow",
        "difficulty": "easy",
        "platform_target": None,
        "language": "fr",
        "description": "Sections presentation des forums FR ou poster avec signature et lien",
        "tags": ["forum", "presentation", "signature", "fr"],
    },
    {
        "name": "Blogs acceptant articles invites (Write for us FR)",
        "category": "guest_posts",
        "subcategory": None,
        "query_template": '"{keyword}" "write for us" OR "ecrivez pour nous" OR "proposer un article" "guidelines" OR "charte" site:.fr',
        "expected_link_type": "dofollow",
        "difficulty": "hard",
        "platform_target": None,
        "language": "fr",
        "description": "Blogs FR avec une page dediee pour soumettre des articles invites",
        "tags": ["guest-post", "write-for-us", "article-invite", "fr"],
    },
]
